name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install musl toolchain
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        export ARCH=${{ matrix.arch }}
        export OS_NAME=${{ runner.os }}
        [ $ARCH = x86_64  ] && export FILE="x86_64-linux-musl-cross";
        [ $OS_NAME = Linux ] && export URL="https://more.musl.cc/9/x86_64-linux-musl/$FILE.tgz";
        [ $OS_NAME = macOS ] && export URL="https://mac.musl.cc/$FILE.tgz";
        wget $URL;
        tar -xf $FILE.tgz;
        echo "::add-path::$PWD/$FILE/bin"

    - name: Build
      run: |
        make ARCH=${{ matrix.arch }}
